# Generated by Django 3.1.2 on 2022-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezza', '0007_auto_20220130_1426'),
        ('account', '0002_auto_20220128_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='talent_applications', to='mezza.Event'),
        ),
    ]
