# Generated by Django 3.1.2 on 2022-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezza', '0007_auto_20220130_1426'),
        ('account', '0003_talent_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='confirmed_events',
            field=models.ManyToManyField(blank=True, related_name='talent_confirmed', to='mezza.Event'),
        ),
    ]
