# Generated by Django 3.1.2 on 2022-01-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezza', '0007_auto_20220130_1426'),
        ('account', '0004_talent_confirmed_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='talent_offers', to='mezza.Event'),
        ),
    ]
