# Generated by Django 3.1.2 on 2022-02-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_talent_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='venue',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Post code'),
        ),
    ]
