# Generated by Django 3.1.2 on 2022-02-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220212_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
