# Generated by Django 3.1.2 on 2022-02-24 23:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220212_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='tag_select',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Night Club', 'Night Club'), ('Restaurant', 'Restaurant'), ('Jazz Club', 'Jazz ')], default='Night Club', max_length=44),
        ),
    ]
