# Generated by Django 3.1.2 on 2022-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_venue_tag_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='tag_select',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Night Club', 'Night Club'), ('Restaurant', 'Restaurant'), ('Jazz Club', 'Jazz ')], default='Rock', max_length=20),
        ),
    ]
