# Generated by Django 3.1.2 on 2022-02-27 18:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220227_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tags', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='venue',
            name='tag_select',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Night Club', 'Night Club'), ('Restaurant', 'Restaurant'), ('Jazz Club', 'Jazz ')], max_length=44),
        ),
        migrations.AddField(
            model_name='venue',
            name='account_tags',
            field=models.ManyToManyField(to='account.AccountTags'),
        ),
    ]
