# Generated by Django 3.1.2 on 2022-02-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_venue_tag_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='account_tags',
            field=models.ManyToManyField(to='account.AccountTags'),
        ),
    ]
