# Generated by Django 3.1.2 on 2022-02-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_talent_account_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='description',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
