# Generated by Django 3.1.2 on 2022-02-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20220227_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='tags',
        ),
    ]
