# Generated by Django 3.1.2 on 2022-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220228_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
