# Generated by Django 3.1.2 on 2022-01-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='instrument',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
