# Generated by Django 3.1.2 on 2022-01-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20220128_2000'),
        ('mezza', '0003_auto_20220126_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Event Wage')),
                ('talent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.talent')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.venue')),
            ],
        ),
    ]
