# Generated by Django 3.1.2 on 2022-01-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezza', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
