# Generated by Django 3.1.2 on 2022-01-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220128_2000'),
        ('mezza', '0005_event_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='applicants',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_applicants', to='account.Talent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_talent', to='account.talent'),
        ),
    ]
