# Generated by Django 3.1.2 on 2022-01-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_talent_offers'),
        ('mezza', '0007_auto_20220130_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='event_offers', to='account.Talent'),
        ),
    ]
