# Generated by Django 3.1.2 on 2022-01-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_talent_offers'),
        ('mezza', '0010_auto_20220131_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='talent',
        ),
        migrations.AddField(
            model_name='event',
            name='talent',
            field=models.ManyToManyField(blank=True, related_name='event_talent', to='account.Talent'),
        ),
    ]
