# Generated by Django 3.1.2 on 2022-01-31 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_talent_offers'),
        ('mezza', '0011_auto_20220131_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='talent',
        ),
        migrations.AddField(
            model_name='event',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_talent', to='account.talent'),
        ),
    ]
