# Generated by Django 3.1.2 on 2022-02-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezza', '0012_auto_20220131_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
