# Generated by Django 3.1.2 on 2022-02-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20220227_2012'),
        ('mezza', '0013_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_tags',
            field=models.ManyToManyField(to='account.AccountTags'),
        ),
    ]
