# Generated by Django 3.1.2 on 2022-03-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezza', '0014_event_event_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
    ]
